const express = require("express");
const PDFDocument = require("pdfkit");

const Profile = require("../models/Profile");

const router = express.Router();

router.get("/", async (req, res) => {
  try {

    const profile =
      await Profile.findOne().sort({
        _id: -1,
      });

    const doc =
      new PDFDocument();

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      "attachment; filename=farmer-report.pdf"
    );

    doc.pipe(res);

    doc
      .fontSize(22)
      .text(
        "Smart Farmer Report",
        {
          align: "center",
        }
      );

    doc.moveDown();

    doc
      .fontSize(16)
      .text(
        `Name: ${profile?.name || "N/A"}`
      );

    doc.text(
      `Village: ${profile?.village || "N/A"}`
    );

    doc.text(
      `District: ${profile?.district || "N/A"}`
    );

    doc.text(
      `State: ${profile?.state || "N/A"}`
    );

    doc.text(
      `Farm Size: ${profile?.farmSize || "N/A"}`
    );

    doc.text(
      `Soil Type: ${profile?.soilType || "N/A"}`
    );

    doc.text(
      `Preferred Crop: ${profile?.preferredCrop || "N/A"}`
    );

    doc.moveDown();

    doc.text(
      "Generated by Smart Farmer Advisory System"
    );

    doc.end();

  } catch (error) {

    console.log(error);

    res.status(500).json({
      message:
        "Failed to generate report",
    });

  }
});

module.exports = router;